name: phockup
version: '1.2.2'
summary: Photo and video sorting tool
description: |
  Media sorting tool to organize photos and videos from your camera in folders by year, month and day.
  The software will collect all files from the input directory and copy them to the output directory without
  changing the files content. It will only rename the files and place them in the proper directory for year, month and day.

confinement: strict
architectures: [amd64]
grade: stable

apps:
  phockup:
    command: phockup.sh
    plugs: [home, removable-media]

parts:
  files:
    plugin: dump
    source: .
    organize:
      phockup.py: lib/phockup/phockup.py
      license: lib/phockup/license
    after: [integration, source]

  source:
    source: https://github.com/ivandokov/phockup.git
    source-tag: $SNAPCRAFT_PROJECT_VERSION
    plugin: python

  integration:
    plugin: nil
    stage-packages:
      - locales-all
      - libimage-exiftool-perl
      - libc-bin
